name: Terraform CI/CD

on:
  pull_request:
    branches: [dev, main]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform_ci.yml'
  push:
    branches: [main]
    paths:
      - 'terraform/**'

jobs:
  terraform:
    name: Terraform Plan / Apply
    runs-on: ubuntu-latest

    env:
      TF_VAR_snowflake_organization: ${{ secrets.SNOWFLAKE_ORGANIZATION }}
      TF_VAR_snowflake_account_name: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      TF_VAR_snowflake_username:     ${{ secrets.SNOWFLAKE_TF_USERNAME }}
      TF_VAR_snowflake_password:     ${{ secrets.SNOWFLAKE_TF_PASSWORD }}
      TF_VAR_dbt_svc_password:       ${{ secrets.SNOWFLAKE_PASSWORD }}
      TF_VAR_loader_svc_password:    ${{ secrets.SNOWFLAKE_PASSWORD }}
      TF_VAR_reporter_svc_password:  ${{ secrets.SNOWFLAKE_PASSWORD }}
      AWS_ACCESS_KEY_ID:             ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:         ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION:                    ${{ secrets.AWS_REGION }}

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.14"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Plan
        run: terraform plan -no-color
        continue-on-error: false

      # Apply only on merge to main
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
